### PR TITLE
feat(tests): pass the server.on function to backend tests

### PR DESCRIPTION
**Pull request by philbooth**
@chilts @rfk

This is a proposal to enable functional tests of server emitted events. It just involves passing the bound `server.on` function to the backend tests, so that they can listen for any events of interest.

For usage, see the incoming fxa-auth-db-server PR (I'll refer to this PR from that one).

Not sure how you guys feel about it or where it lies on the hackishness spectrum, but it was the simplest thing I could think of to do what I wanted. Thoughts?

### CODE REVIEW

**Comment by rfk** [comment]
I'm fine with the hackishness level here, but it may be simpler/clearer to pass the entire `server` object rather than just a single method.

**Comment by philbooth** [comment]
Actually, passing in `server` was what I did initially. My reason for changing it was concern that the functional tests now had a level of access/power that they shouldn't have. Will change back.

**Comment by philbooth** [comment]
@rfk pushed

**Comment by rfk** [comment]
thanks @philbooth!

**Pull request merged**
