### PR TITLE
Fixes #13 - Switch logger to mozlog from bunyan

### LINKED ISSUE #13: Use mozlog for logging
Mozlogify all the things

### PR DESCRIPTION
**Pull request by chilts**

### CODE REVIEW

**Comment by chilts** [comment]
This is pretty much a minimal set of changes needed to use mozlog which may well be all that's needed.

Am just curious about the formatting of the log output though and wonder if I've done something strange of if it's right. Here's a couple of examples, the first line showing what was originally there, the 2nd line the new output.

Server Start

```
{"name":"db-api","hostname":"tiger","pid":13703,"level":30,"op":"server.start","msg":"","time":"2015-03-09T02:08:05.389Z","v":0}

{"Timestamp":1425866885390000000,"Logger":"fxa-auth-db-server","Type":"bin.server.start","Severity":6,"Pid":13703,"EnvVersion":"2.0","Fields":{"port":8000}}
```

Create Account

```
{"name":"db-api","hostname":"tiger","pid":13777,"level":30,"op":"request.summary","code":200,"route":"putaccountid","method":"PUT","path":"/account/6044486dd15b42e08b1fb9167415b9ac","t":5,"msg":"","time":"2015-03-09T02:12:50.909Z","v":0}

{"Timestamp":1425867170909000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":13777,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"route":"putaccountid","method":"PUT","path":"/account/6044486dd15b42e08b1fb9167415b9ac","t":5}}
```

Get PasswordForgotToken

```
{"name":"db-api","hostname":"tiger","pid":13703,"level":40,"op":"request.summary","code":404,"route":"getpasswordforgottokenid","method":"GET","path":"/passwordForgotToken/266fd690895c8b0086bb2c83e4b3b41c128746125f28b5429938765279673d62","err":{"message":"Not Found","errno":116,"error":"Not Found","code":404},"t":1,"msg":"","time":"2015-03-09T02:09:41.270Z","v":0}

{"Timestamp":1425866981271000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":4,"Pid":13703,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":404,"route":"getpasswordforgottokenid","method":"GET","path":"/passwordForgotToken/266fd690895c8b0086bb2c83e4b3b41c128746125f28b5429938765279673d62","err":"{\"message\":\"Not Found\",\"errno\":116,\"error\":\"Not Found\",\"code\":404}","t":1}}
```


Delete PasswordForgotToken

```
{"name":"db-api","hostname":"tiger","pid":13703,"level":30,"op":"request.summary","code":200,"route":"deletepasswordforgottokenid","method":"DELETE","path":"/passwordForgotToken/266fd690895c8b0086bb2c83e4b3b41c128746125f28b5429938765279673d62","t":2,"msg":"","time":"2015-03-09T02:09:24.277Z","v":0}

{"Timestamp":1425866964277000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":13703,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":200,"route":"deletepasswordforgottokenid","method":"DELETE","path":"/passwordForgotToken/266fd690895c8b0086bb2c83e4b3b41c128746125f28b5429938765279673d62","t":2}}
```

Am just wondering about a few things:

* I guess if an object is passed it is now under `Fields` instead of being merged in with the other data. Is this what's wanted?
* The error in the Get PasswordForgotToken looks like it's a string. I remember conversation about this being the case, so just wanted to check that again, this is correct?
* I set the `config.logging.app` to be 'fxa-auth-db-server' which I assume is okay, even though the original name was `db-api`.

Anyone see anything incorrect here? /cc @seanmonstar @rfk @dannycoates 

(Note: just wanted to do this repo prior to `fxa-auth-db-mysql` to make sure it's on the right lines.)

**Comment by dannycoates** [comment]
aside from `"op":"request.summary"` from https://github.com/mozilla/fxa-auth-db-server/blob/master/index.js#L19 being redundant this looks good to me.

**Comment by chilts** [comment]
Ah cool. I'll do a separate PR to remove those from the other side once this one is merged. Ta.

**Comment by seanmonstar** [comment]
r+

**Pull request merged**
