### PR TITLE
refactor(lib): Move a few source files into lib/

### PR DESCRIPTION
**Pull request by chilts**
Both bin/ and config/ directories have been left alone.

### CODE REVIEW

**Comment by chilts** [comment]
I guess `package.json` and `npm-shrinkwrap.json` need updating in fxa-auth-server after this, though it's already pointing at #master ... perhaps not! :question:

**Comment by chilts** [comment]
Anyone r?

**Comment by dannycoates** [comment]
:+1:

**Comment by chilts** [comment]
Thanks @dannycoates :star:

**Pull request merged**
