### PR TITLE
fix(shrinkwrap): as discussed, only "top-level" repos get shrunkwrapped

### PR DESCRIPTION
**Pull request by jrgm**
@chilts r?

### CODE REVIEW

**Comment by pdehaan** [comment]
We should remove the **grunt-nsp-shrinkwrap** package in [package.json](https://github.com/mozilla/fxa-auth-db-mem/blob/7b17159f63d54e973bef25e3583aec42c7ead013/package.json#L35), and I think this repo had a reference in the [.travis.yml](https://github.com/mozilla/fxa-auth-db-mem/blob/7b17159f63d54e973bef25e3583aec42c7ead013/.travis.yml#L19) file.

Oddly, I don't think this repo split apart the Gruntfile.js into separate _grunttasks/*_ tasks and added the **bump** module for versioning -- so no need to remove from _grunttasks/bump.js_, like the other repo.

**Comment by pdehaan** [comment]
Ah yes, the Travis build failed because the .travis.yml is trying to validate the now non-existent file.

**Comment by jrgm** [comment]
@pdehaan - thanks. Forgot about that link. Will clean up and re-push.

**Comment by pdehaan** [comment]
@jrgm:

**Comment by chilts** [comment]
This repo is interesting. From the perspective of the backend, this is theoretically at the same viewpoint as the `fxa-auth-db-mysql` repo i.e. it _is_ a top level repo. However, practically it is only being used as a test server from the `fxa-auth-server` as a devDependency, so no! The latter wins.

On that point, and after having @pdehaan's review, lgtm.

**Comment by jrgm** [comment]
Yeah, I didn't actually mean to suggest it wasn't "top-level", just its relationship to "fxa-auth-server", and the latter is what ships.

**Comment by jrgm** [comment]
Man, I tortured English grammar in the previous sentence.

**Comment by pdehaan** [comment]
So, if I understand @chilts' comment correctly, this repo will then only get shrunkwrap-linted if we generate the **fxa-auth-server**'s _npm-shrinkwrap.json_ file with the `--dev` flag ([which it looks like we do](https://github.com/mozilla/fxa-auth-server/blob/dd5f7b7567a484160d4ee1718887ce1c89f27eb6/npm-shrinkwrap.json#L1545) -- or at least the last person did, not sure how consistent it is).

**Comment by chilts** [comment]
Yeah, I think we decided somewhere sometime that we should always include the `--dev` flag. I think and hope that's what everyone is doing anyway, it certainly looks like it.

**Comment by pdehaan** [comment]
@chilts: Yeah, I keep meaning to add an `npm run shrinkwrap` task to each repo that just proxies `npm shrinkwrap --dev` so there would be a consistent way to run shrinkwrap in each repo, but I haven't gotten around to it yet (plus, then we can write some fancy `postshrinkwrap` script/hook which automatically runs the security checker on the newly generated npm-shrinkwrap.json files).

I think @jrgm was also investigating and/or patching the [uber/**npm-shrinkwrap**](https://github.com/uber/npm-shrinkwrap) tool, which looks pretty interesting.

**Comment by chilts** [comment]
@pdehaan: And I've seen @jrgm did some fancy-smancey other stuff too, but I can't find it. I've certainly done something like this before (usually when something seemed to go wrong prior) to get a clean slate but never quite figured out if we need it all every time:

1. rm -rf npm-shrinkwrap.json node_modules
1. npm cache clean
1. npm install
1. npm shrinkwrap --dev
1. ???
1. Profit!

I'm not sure about the last two points.

**Pull request merged**
