### PR TITLE
Added checkPassword API

### PR DESCRIPTION
**Pull request by eoger**
Part of https://github.com/mozilla/fxa-auth-db-server/issues/88

### CODE REVIEW

**Comment by chilts** [comment]
r+.

**Comment by eoger** [comment]
I also added my fxa-auth-db-server fork to package.json so travis can test everything.

**Comment by chilts** [comment]
Awesome. Thanks for doing that do the tests pass. Once you put the package.json back I'll merge. Note: if you squash these two commits back into one and force push, then we'll just have one nice commit in history. Let me know if you need help with that. :) r+

**Comment by eoger** [comment]
package.json temp fix removed ;)

**Pull request merged**
